/**
 * Section represents a section inside of an editable object.
 */
export default class Section {
    /**
     * Creates a new Section entity.
     *
     * @example
     * var s = new Section('myPlugin', '1.0', {enableTables: true}, {innerHTML: '...'});
     *
     * @param {string} name The plugin's name (e.g. mediumjs)
     * @param {string} version The plugin's version (e.g. 0.1.1)
     * @param {Object} args Arguments you want to pass to the plugin (e.g. {enableTables: true})
     * @param {Object} data Data which is being passed to the plugin, mostly generated by a parser.
     */
    constructor(name, version, args, data) {
        // The id is primarily used for react to identify
        // the section when rendering.
        // TODO Math.random() should be fine for now but it's probably smart to use uuids.
        this.id = Math.random();

        this.name = name || '';
        this.version = version || '';
        this.args = args || {};
        this.data = data || {};
    }
}
