// flow-typed signature: 002db0b0abdfb4acfa5e34095f773869
// flow-typed version: <<STUB>>/chokidar-cli_v^1.2.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chokidar-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chokidar-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chokidar-cli/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chokidar-cli/index' {
  declare module.exports: $Exports<'chokidar-cli'>;
}
declare module 'chokidar-cli/index.js' {
  declare module.exports: $Exports<'chokidar-cli'>;
}
declare module 'chokidar-cli/utils.js' {
  declare module.exports: $Exports<'chokidar-cli/utils'>;
}
