// flow-typed signature: d46dfd1c98ddc185c2193e51699b04dc
// flow-typed version: <<STUB>>/coveralls_v^2.13.1/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'coveralls'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'coveralls' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'coveralls/bin/coveralls' {
  declare module.exports: any;
}

declare module 'coveralls/fixtures/lib/index' {
  declare module.exports: any;
}

declare module 'coveralls/lib/convertLcovToCoveralls' {
  declare module.exports: any;
}

declare module 'coveralls/lib/detectLocalGit' {
  declare module.exports: any;
}

declare module 'coveralls/lib/fetchGitData' {
  declare module.exports: any;
}

declare module 'coveralls/lib/getOptions' {
  declare module.exports: any;
}

declare module 'coveralls/lib/handleInput' {
  declare module.exports: any;
}

declare module 'coveralls/lib/logger' {
  declare module.exports: any;
}

declare module 'coveralls/lib/sendToCoveralls' {
  declare module.exports: any;
}

// Filename aliases
declare module 'coveralls/bin/coveralls.js' {
  declare module.exports: $Exports<'coveralls/bin/coveralls'>;
}
declare module 'coveralls/fixtures/lib/index.js' {
  declare module.exports: $Exports<'coveralls/fixtures/lib/index'>;
}
declare module 'coveralls/index' {
  declare module.exports: $Exports<'coveralls'>;
}
declare module 'coveralls/index.js' {
  declare module.exports: $Exports<'coveralls'>;
}
declare module 'coveralls/lib/convertLcovToCoveralls.js' {
  declare module.exports: $Exports<'coveralls/lib/convertLcovToCoveralls'>;
}
declare module 'coveralls/lib/detectLocalGit.js' {
  declare module.exports: $Exports<'coveralls/lib/detectLocalGit'>;
}
declare module 'coveralls/lib/fetchGitData.js' {
  declare module.exports: $Exports<'coveralls/lib/fetchGitData'>;
}
declare module 'coveralls/lib/getOptions.js' {
  declare module.exports: $Exports<'coveralls/lib/getOptions'>;
}
declare module 'coveralls/lib/handleInput.js' {
  declare module.exports: $Exports<'coveralls/lib/handleInput'>;
}
declare module 'coveralls/lib/logger.js' {
  declare module.exports: $Exports<'coveralls/lib/logger'>;
}
declare module 'coveralls/lib/sendToCoveralls.js' {
  declare module.exports: $Exports<'coveralls/lib/sendToCoveralls'>;
}
