// flow-typed signature: a33f75a671743cb3f7ab7f9f008e20e2
// flow-typed version: <<STUB>>/deep-rename-keys_v^0.2.1/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'deep-rename-keys'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'deep-rename-keys' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'deep-rename-keys/index' {
  declare module.exports: $Exports<'deep-rename-keys'>;
}
declare module 'deep-rename-keys/index.js' {
  declare module.exports: $Exports<'deep-rename-keys'>;
}
