// flow-typed signature: dc14f0328181b3518efc4574a9b19b0f
// flow-typed version: <<STUB>>/device.js_v^2.3.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'device.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'device.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'device.js/dist/device.es' {
  declare module.exports: any;
}

declare module 'device.js/dist/device' {
  declare module.exports: any;
}

declare module 'device.js/dist/device.umd' {
  declare module.exports: any;
}

declare module 'device.js/src/device' {
  declare module.exports: any;
}

// Filename aliases
declare module 'device.js/dist/device.es.js' {
  declare module.exports: $Exports<'device.js/dist/device.es'>;
}
declare module 'device.js/dist/device.js' {
  declare module.exports: $Exports<'device.js/dist/device'>;
}
declare module 'device.js/dist/device.umd.js' {
  declare module.exports: $Exports<'device.js/dist/device.umd'>;
}
declare module 'device.js/src/device.js' {
  declare module.exports: $Exports<'device.js/src/device'>;
}
