// flow-typed signature: c42e3dbff2db7a16249ee6d3c6337963
// flow-typed version: <<STUB>>/device.js_v^0.1.2/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'device.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'device.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'device.js/device' {
  declare module.exports: any;
}

// Filename aliases
declare module 'device.js/device.js' {
  declare module.exports: $Exports<'device.js/device'>;
}
