// flow-typed signature: 8e44fa8b6ad074edec3c8f3a95f028b2
// flow-typed version: <<STUB>>/dnd-core_v^2.3.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dnd-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'dnd-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dnd-core/lib/actions/dragDrop' {
  declare module.exports: any;
}

declare module 'dnd-core/lib/actions/registry' {
  declare module.exports: any;
}

declare module 'dnd-core/lib/backends/createTestBackend' {
  declare module.exports: any;
}

declare module 'dnd-core/lib/DragDropManager' {
  declare module.exports: any;
}

declare module 'dnd-core/lib/DragDropMonitor' {
  declare module.exports: any;
}

declare module 'dnd-core/lib/DragSource' {
  declare module.exports: any;
}

declare module 'dnd-core/lib/DropTarget' {
  declare module.exports: any;
}

declare module 'dnd-core/lib/HandlerRegistry' {
  declare module.exports: any;
}

declare module 'dnd-core/lib/index' {
  declare module.exports: any;
}

declare module 'dnd-core/lib/reducers/dirtyHandlerIds' {
  declare module.exports: any;
}

declare module 'dnd-core/lib/reducers/dragOffset' {
  declare module.exports: any;
}

declare module 'dnd-core/lib/reducers/dragOperation' {
  declare module.exports: any;
}

declare module 'dnd-core/lib/reducers/index' {
  declare module.exports: any;
}

declare module 'dnd-core/lib/reducers/refCount' {
  declare module.exports: any;
}

declare module 'dnd-core/lib/reducers/stateId' {
  declare module.exports: any;
}

declare module 'dnd-core/lib/utils/getNextUniqueId' {
  declare module.exports: any;
}

declare module 'dnd-core/lib/utils/matchesType' {
  declare module.exports: any;
}

declare module 'dnd-core/src/actions/dragDrop' {
  declare module.exports: any;
}

declare module 'dnd-core/src/actions/registry' {
  declare module.exports: any;
}

declare module 'dnd-core/src/backends/createTestBackend' {
  declare module.exports: any;
}

declare module 'dnd-core/src/DragDropManager' {
  declare module.exports: any;
}

declare module 'dnd-core/src/DragDropMonitor' {
  declare module.exports: any;
}

declare module 'dnd-core/src/DragSource' {
  declare module.exports: any;
}

declare module 'dnd-core/src/DropTarget' {
  declare module.exports: any;
}

declare module 'dnd-core/src/HandlerRegistry' {
  declare module.exports: any;
}

declare module 'dnd-core/src/index' {
  declare module.exports: any;
}

declare module 'dnd-core/src/reducers/dirtyHandlerIds' {
  declare module.exports: any;
}

declare module 'dnd-core/src/reducers/dragOffset' {
  declare module.exports: any;
}

declare module 'dnd-core/src/reducers/dragOperation' {
  declare module.exports: any;
}

declare module 'dnd-core/src/reducers/index' {
  declare module.exports: any;
}

declare module 'dnd-core/src/reducers/refCount' {
  declare module.exports: any;
}

declare module 'dnd-core/src/reducers/stateId' {
  declare module.exports: any;
}

declare module 'dnd-core/src/utils/getNextUniqueId' {
  declare module.exports: any;
}

declare module 'dnd-core/src/utils/matchesType' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dnd-core/lib/actions/dragDrop.js' {
  declare module.exports: $Exports<'dnd-core/lib/actions/dragDrop'>;
}
declare module 'dnd-core/lib/actions/registry.js' {
  declare module.exports: $Exports<'dnd-core/lib/actions/registry'>;
}
declare module 'dnd-core/lib/backends/createTestBackend.js' {
  declare module.exports: $Exports<'dnd-core/lib/backends/createTestBackend'>;
}
declare module 'dnd-core/lib/DragDropManager.js' {
  declare module.exports: $Exports<'dnd-core/lib/DragDropManager'>;
}
declare module 'dnd-core/lib/DragDropMonitor.js' {
  declare module.exports: $Exports<'dnd-core/lib/DragDropMonitor'>;
}
declare module 'dnd-core/lib/DragSource.js' {
  declare module.exports: $Exports<'dnd-core/lib/DragSource'>;
}
declare module 'dnd-core/lib/DropTarget.js' {
  declare module.exports: $Exports<'dnd-core/lib/DropTarget'>;
}
declare module 'dnd-core/lib/HandlerRegistry.js' {
  declare module.exports: $Exports<'dnd-core/lib/HandlerRegistry'>;
}
declare module 'dnd-core/lib/index.js' {
  declare module.exports: $Exports<'dnd-core/lib/index'>;
}
declare module 'dnd-core/lib/reducers/dirtyHandlerIds.js' {
  declare module.exports: $Exports<'dnd-core/lib/reducers/dirtyHandlerIds'>;
}
declare module 'dnd-core/lib/reducers/dragOffset.js' {
  declare module.exports: $Exports<'dnd-core/lib/reducers/dragOffset'>;
}
declare module 'dnd-core/lib/reducers/dragOperation.js' {
  declare module.exports: $Exports<'dnd-core/lib/reducers/dragOperation'>;
}
declare module 'dnd-core/lib/reducers/index.js' {
  declare module.exports: $Exports<'dnd-core/lib/reducers/index'>;
}
declare module 'dnd-core/lib/reducers/refCount.js' {
  declare module.exports: $Exports<'dnd-core/lib/reducers/refCount'>;
}
declare module 'dnd-core/lib/reducers/stateId.js' {
  declare module.exports: $Exports<'dnd-core/lib/reducers/stateId'>;
}
declare module 'dnd-core/lib/utils/getNextUniqueId.js' {
  declare module.exports: $Exports<'dnd-core/lib/utils/getNextUniqueId'>;
}
declare module 'dnd-core/lib/utils/matchesType.js' {
  declare module.exports: $Exports<'dnd-core/lib/utils/matchesType'>;
}
declare module 'dnd-core/src/actions/dragDrop.js' {
  declare module.exports: $Exports<'dnd-core/src/actions/dragDrop'>;
}
declare module 'dnd-core/src/actions/registry.js' {
  declare module.exports: $Exports<'dnd-core/src/actions/registry'>;
}
declare module 'dnd-core/src/backends/createTestBackend.js' {
  declare module.exports: $Exports<'dnd-core/src/backends/createTestBackend'>;
}
declare module 'dnd-core/src/DragDropManager.js' {
  declare module.exports: $Exports<'dnd-core/src/DragDropManager'>;
}
declare module 'dnd-core/src/DragDropMonitor.js' {
  declare module.exports: $Exports<'dnd-core/src/DragDropMonitor'>;
}
declare module 'dnd-core/src/DragSource.js' {
  declare module.exports: $Exports<'dnd-core/src/DragSource'>;
}
declare module 'dnd-core/src/DropTarget.js' {
  declare module.exports: $Exports<'dnd-core/src/DropTarget'>;
}
declare module 'dnd-core/src/HandlerRegistry.js' {
  declare module.exports: $Exports<'dnd-core/src/HandlerRegistry'>;
}
declare module 'dnd-core/src/index.js' {
  declare module.exports: $Exports<'dnd-core/src/index'>;
}
declare module 'dnd-core/src/reducers/dirtyHandlerIds.js' {
  declare module.exports: $Exports<'dnd-core/src/reducers/dirtyHandlerIds'>;
}
declare module 'dnd-core/src/reducers/dragOffset.js' {
  declare module.exports: $Exports<'dnd-core/src/reducers/dragOffset'>;
}
declare module 'dnd-core/src/reducers/dragOperation.js' {
  declare module.exports: $Exports<'dnd-core/src/reducers/dragOperation'>;
}
declare module 'dnd-core/src/reducers/index.js' {
  declare module.exports: $Exports<'dnd-core/src/reducers/index'>;
}
declare module 'dnd-core/src/reducers/refCount.js' {
  declare module.exports: $Exports<'dnd-core/src/reducers/refCount'>;
}
declare module 'dnd-core/src/reducers/stateId.js' {
  declare module.exports: $Exports<'dnd-core/src/reducers/stateId'>;
}
declare module 'dnd-core/src/utils/getNextUniqueId.js' {
  declare module.exports: $Exports<'dnd-core/src/utils/getNextUniqueId'>;
}
declare module 'dnd-core/src/utils/matchesType.js' {
  declare module.exports: $Exports<'dnd-core/src/utils/matchesType'>;
}
