// flow-typed signature: 84f76be7c877211ded51265097e02527
// flow-typed version: <<STUB>>/element-resize-event_v^2.0.9/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'element-resize-event'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'element-resize-event' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'element-resize-event/example/bundle' {
  declare module.exports: any;
}

declare module 'element-resize-event/example/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'element-resize-event/example/bundle.js' {
  declare module.exports: $Exports<'element-resize-event/example/bundle'>;
}
declare module 'element-resize-event/example/index.js' {
  declare module.exports: $Exports<'element-resize-event/example/index'>;
}
declare module 'element-resize-event/index' {
  declare module.exports: $Exports<'element-resize-event'>;
}
declare module 'element-resize-event/index.js' {
  declare module.exports: $Exports<'element-resize-event'>;
}
