// flow-typed signature: 1f43a118b3433c8ff1dedc77f1c77333
// flow-typed version: <<STUB>>/ory-editor-ui_v0.0.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ory-editor-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ory-editor-ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ory-editor-ui/lib/BottomToolbar/index' {
  declare module.exports: any;
}

declare module 'ory-editor-ui/lib/DisplayModeToggle/Button/index' {
  declare module.exports: any;
}

declare module 'ory-editor-ui/lib/DisplayModeToggle/index' {
  declare module.exports: any;
}

declare module 'ory-editor-ui/lib/DisplayModeToggle/ToggleEdit/index' {
  declare module.exports: any;
}

declare module 'ory-editor-ui/lib/DisplayModeToggle/ToggleInsert/index' {
  declare module.exports: any;
}

declare module 'ory-editor-ui/lib/DisplayModeToggle/ToggleLayout/index' {
  declare module.exports: any;
}

declare module 'ory-editor-ui/lib/DisplayModeToggle/TogglePreview/index' {
  declare module.exports: any;
}

declare module 'ory-editor-ui/lib/DisplayModeToggle/ToggleResize/index' {
  declare module.exports: any;
}

declare module 'ory-editor-ui/lib/index' {
  declare module.exports: any;
}

declare module 'ory-editor-ui/lib/Notifier/index' {
  declare module.exports: any;
}

declare module 'ory-editor-ui/lib/Provider/index' {
  declare module.exports: any;
}

declare module 'ory-editor-ui/lib/ThemeProvider/DarkTheme/index' {
  declare module.exports: any;
}

declare module 'ory-editor-ui/lib/ThemeProvider/index' {
  declare module.exports: any;
}

declare module 'ory-editor-ui/lib/Toolbar/Draggable/helper/index' {
  declare module.exports: any;
}

declare module 'ory-editor-ui/lib/Toolbar/Draggable/index' {
  declare module.exports: any;
}

declare module 'ory-editor-ui/lib/Toolbar/index' {
  declare module.exports: any;
}

declare module 'ory-editor-ui/lib/Toolbar/Item/index' {
  declare module.exports: any;
}

declare module 'ory-editor-ui/lib/Trash/index' {
  declare module.exports: any;
}

declare module 'ory-editor-ui/src/BottomToolbar/index' {
  declare module.exports: any;
}

declare module 'ory-editor-ui/src/DisplayModeToggle/Button/index' {
  declare module.exports: any;
}

declare module 'ory-editor-ui/src/DisplayModeToggle/index' {
  declare module.exports: any;
}

declare module 'ory-editor-ui/src/DisplayModeToggle/ToggleEdit/index' {
  declare module.exports: any;
}

declare module 'ory-editor-ui/src/DisplayModeToggle/ToggleInsert/index' {
  declare module.exports: any;
}

declare module 'ory-editor-ui/src/DisplayModeToggle/ToggleLayout/index' {
  declare module.exports: any;
}

declare module 'ory-editor-ui/src/DisplayModeToggle/TogglePreview/index' {
  declare module.exports: any;
}

declare module 'ory-editor-ui/src/DisplayModeToggle/ToggleResize/index' {
  declare module.exports: any;
}

declare module 'ory-editor-ui/src/index' {
  declare module.exports: any;
}

declare module 'ory-editor-ui/src/Notifier/index' {
  declare module.exports: any;
}

declare module 'ory-editor-ui/src/Provider/index' {
  declare module.exports: any;
}

declare module 'ory-editor-ui/src/ThemeProvider/DarkTheme/index' {
  declare module.exports: any;
}

declare module 'ory-editor-ui/src/ThemeProvider/index' {
  declare module.exports: any;
}

declare module 'ory-editor-ui/src/Toolbar/Draggable/helper/index' {
  declare module.exports: any;
}

declare module 'ory-editor-ui/src/Toolbar/Draggable/index' {
  declare module.exports: any;
}

declare module 'ory-editor-ui/src/Toolbar/index' {
  declare module.exports: any;
}

declare module 'ory-editor-ui/src/Toolbar/Item/index' {
  declare module.exports: any;
}

declare module 'ory-editor-ui/src/Trash/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ory-editor-ui/lib/BottomToolbar/index.js' {
  declare module.exports: $Exports<'ory-editor-ui/lib/BottomToolbar/index'>;
}
declare module 'ory-editor-ui/lib/DisplayModeToggle/Button/index.js' {
  declare module.exports: $Exports<'ory-editor-ui/lib/DisplayModeToggle/Button/index'>;
}
declare module 'ory-editor-ui/lib/DisplayModeToggle/index.js' {
  declare module.exports: $Exports<'ory-editor-ui/lib/DisplayModeToggle/index'>;
}
declare module 'ory-editor-ui/lib/DisplayModeToggle/ToggleEdit/index.js' {
  declare module.exports: $Exports<'ory-editor-ui/lib/DisplayModeToggle/ToggleEdit/index'>;
}
declare module 'ory-editor-ui/lib/DisplayModeToggle/ToggleInsert/index.js' {
  declare module.exports: $Exports<'ory-editor-ui/lib/DisplayModeToggle/ToggleInsert/index'>;
}
declare module 'ory-editor-ui/lib/DisplayModeToggle/ToggleLayout/index.js' {
  declare module.exports: $Exports<'ory-editor-ui/lib/DisplayModeToggle/ToggleLayout/index'>;
}
declare module 'ory-editor-ui/lib/DisplayModeToggle/TogglePreview/index.js' {
  declare module.exports: $Exports<'ory-editor-ui/lib/DisplayModeToggle/TogglePreview/index'>;
}
declare module 'ory-editor-ui/lib/DisplayModeToggle/ToggleResize/index.js' {
  declare module.exports: $Exports<'ory-editor-ui/lib/DisplayModeToggle/ToggleResize/index'>;
}
declare module 'ory-editor-ui/lib/index.js' {
  declare module.exports: $Exports<'ory-editor-ui/lib/index'>;
}
declare module 'ory-editor-ui/lib/Notifier/index.js' {
  declare module.exports: $Exports<'ory-editor-ui/lib/Notifier/index'>;
}
declare module 'ory-editor-ui/lib/Provider/index.js' {
  declare module.exports: $Exports<'ory-editor-ui/lib/Provider/index'>;
}
declare module 'ory-editor-ui/lib/ThemeProvider/DarkTheme/index.js' {
  declare module.exports: $Exports<'ory-editor-ui/lib/ThemeProvider/DarkTheme/index'>;
}
declare module 'ory-editor-ui/lib/ThemeProvider/index.js' {
  declare module.exports: $Exports<'ory-editor-ui/lib/ThemeProvider/index'>;
}
declare module 'ory-editor-ui/lib/Toolbar/Draggable/helper/index.js' {
  declare module.exports: $Exports<'ory-editor-ui/lib/Toolbar/Draggable/helper/index'>;
}
declare module 'ory-editor-ui/lib/Toolbar/Draggable/index.js' {
  declare module.exports: $Exports<'ory-editor-ui/lib/Toolbar/Draggable/index'>;
}
declare module 'ory-editor-ui/lib/Toolbar/index.js' {
  declare module.exports: $Exports<'ory-editor-ui/lib/Toolbar/index'>;
}
declare module 'ory-editor-ui/lib/Toolbar/Item/index.js' {
  declare module.exports: $Exports<'ory-editor-ui/lib/Toolbar/Item/index'>;
}
declare module 'ory-editor-ui/lib/Trash/index.js' {
  declare module.exports: $Exports<'ory-editor-ui/lib/Trash/index'>;
}
declare module 'ory-editor-ui/src/BottomToolbar/index.js' {
  declare module.exports: $Exports<'ory-editor-ui/src/BottomToolbar/index'>;
}
declare module 'ory-editor-ui/src/DisplayModeToggle/Button/index.js' {
  declare module.exports: $Exports<'ory-editor-ui/src/DisplayModeToggle/Button/index'>;
}
declare module 'ory-editor-ui/src/DisplayModeToggle/index.js' {
  declare module.exports: $Exports<'ory-editor-ui/src/DisplayModeToggle/index'>;
}
declare module 'ory-editor-ui/src/DisplayModeToggle/ToggleEdit/index.js' {
  declare module.exports: $Exports<'ory-editor-ui/src/DisplayModeToggle/ToggleEdit/index'>;
}
declare module 'ory-editor-ui/src/DisplayModeToggle/ToggleInsert/index.js' {
  declare module.exports: $Exports<'ory-editor-ui/src/DisplayModeToggle/ToggleInsert/index'>;
}
declare module 'ory-editor-ui/src/DisplayModeToggle/ToggleLayout/index.js' {
  declare module.exports: $Exports<'ory-editor-ui/src/DisplayModeToggle/ToggleLayout/index'>;
}
declare module 'ory-editor-ui/src/DisplayModeToggle/TogglePreview/index.js' {
  declare module.exports: $Exports<'ory-editor-ui/src/DisplayModeToggle/TogglePreview/index'>;
}
declare module 'ory-editor-ui/src/DisplayModeToggle/ToggleResize/index.js' {
  declare module.exports: $Exports<'ory-editor-ui/src/DisplayModeToggle/ToggleResize/index'>;
}
declare module 'ory-editor-ui/src/index.js' {
  declare module.exports: $Exports<'ory-editor-ui/src/index'>;
}
declare module 'ory-editor-ui/src/Notifier/index.js' {
  declare module.exports: $Exports<'ory-editor-ui/src/Notifier/index'>;
}
declare module 'ory-editor-ui/src/Provider/index.js' {
  declare module.exports: $Exports<'ory-editor-ui/src/Provider/index'>;
}
declare module 'ory-editor-ui/src/ThemeProvider/DarkTheme/index.js' {
  declare module.exports: $Exports<'ory-editor-ui/src/ThemeProvider/DarkTheme/index'>;
}
declare module 'ory-editor-ui/src/ThemeProvider/index.js' {
  declare module.exports: $Exports<'ory-editor-ui/src/ThemeProvider/index'>;
}
declare module 'ory-editor-ui/src/Toolbar/Draggable/helper/index.js' {
  declare module.exports: $Exports<'ory-editor-ui/src/Toolbar/Draggable/helper/index'>;
}
declare module 'ory-editor-ui/src/Toolbar/Draggable/index.js' {
  declare module.exports: $Exports<'ory-editor-ui/src/Toolbar/Draggable/index'>;
}
declare module 'ory-editor-ui/src/Toolbar/index.js' {
  declare module.exports: $Exports<'ory-editor-ui/src/Toolbar/index'>;
}
declare module 'ory-editor-ui/src/Toolbar/Item/index.js' {
  declare module.exports: $Exports<'ory-editor-ui/src/Toolbar/Item/index'>;
}
declare module 'ory-editor-ui/src/Trash/index.js' {
  declare module.exports: $Exports<'ory-editor-ui/src/Trash/index'>;
}
