// flow-typed signature: 70749c001c4e70b13785ccf1a8eb46bf
// flow-typed version: <<STUB>>/ory-editor-core_v0.0.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ory-editor-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ory-editor-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ory-editor-core/flow-typed/npm/classnames_v2.x.x' {
  declare module.exports: any;
}

declare module 'ory-editor-core/flow-typed/npm/deep-equal_vx.x.x' {
  declare module.exports: any;
}

declare module 'ory-editor-core/flow-typed/npm/dnd-core_vx.x.x' {
  declare module.exports: any;
}

declare module 'ory-editor-core/flow-typed/npm/element-resize-event_vx.x.x' {
  declare module.exports: any;
}

declare module 'ory-editor-core/flow-typed/npm/lodash.throttle_vx.x.x' {
  declare module.exports: any;
}

declare module 'ory-editor-core/flow-typed/npm/mousetrap_v1.x.x' {
  declare module.exports: any;
}

declare module 'ory-editor-core/flow-typed/npm/ramda_v0.x.x' {
  declare module.exports: any;
}

declare module 'ory-editor-core/flow-typed/npm/react-dimensions_vx.x.x' {
  declare module.exports: any;
}

declare module 'ory-editor-core/flow-typed/npm/react-dnd_v2.x.x' {
  declare module.exports: any;
}

declare module 'ory-editor-core/flow-typed/npm/react-dnd-html5-backend_v2.1.x' {
  declare module.exports: any;
}

declare module 'ory-editor-core/flow-typed/npm/react-draggable_vx.x.x' {
  declare module.exports: any;
}

declare module 'ory-editor-core/flow-typed/npm/react-hotkeys_vx.x.x' {
  declare module.exports: any;
}

declare module 'ory-editor-core/flow-typed/npm/react-redux_v5.x.x' {
  declare module.exports: any;
}

declare module 'ory-editor-core/flow-typed/npm/redux_v3.x.x' {
  declare module.exports: any;
}

declare module 'ory-editor-core/flow-typed/npm/redux-undo_vx.x.x' {
  declare module.exports: any;
}

declare module 'ory-editor-core/flow-typed/npm/reselect_v3.x.x' {
  declare module.exports: any;
}

declare module 'ory-editor-core/flow-typed/npm/semver_v5.1.x' {
  declare module.exports: any;
}

declare module 'ory-editor-core/flow-typed/npm/uuid_v3.x.x' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/actions/actions.test' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/actions/cell/core' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/actions/cell/drag' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/actions/cell/index' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/actions/cell/insert' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/actions/display' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/actions/editables' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/actions/helpers' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/actions/index' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/actions/setting' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/actions/undo' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/components/Cell/Content/index' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/components/Cell/Draggable/helper/dnd' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/components/Cell/Draggable/index' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/components/Cell/Droppable/helper/dnd' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/components/Cell/Droppable/index' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/components/Cell/Empty/index' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/components/Cell/index' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/components/Cell/Inner/index' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/components/Cell/Layout/index' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/components/Cell/Resizable/helper' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/components/Cell/Resizable/index' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/components/Cell/Rows/index' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/components/Cell/Rows/index.test' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/components/Dimensions/index' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/components/Dimensions/index.test' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/components/DragDropContext/index' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/components/DragDropContext/index.test' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/components/Editable/index' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/components/Editable/Inner/blur' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/components/Editable/Inner/index' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/components/HotKey/Decorator' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/components/HotKey/Handler' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/components/Row/Droppable/dnd' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/components/Row/Droppable/index' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/components/Row/index' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/components/Row/inner' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/const' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/helper/dnd/index' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/helper/shouldComponentUpdate/index' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/helper/throttle/index' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/index' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/index.test' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/reducer/display/index' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/reducer/editable/helper/empty' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/reducer/editable/helper/empty.test' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/reducer/editable/helper/hover' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/reducer/editable/helper/hover.test' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/reducer/editable/helper/inline' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/reducer/editable/helper/inline.test' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/reducer/editable/helper/level' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/reducer/editable/helper/level.test' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/reducer/editable/helper/merge' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/reducer/editable/helper/merge.test' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/reducer/editable/helper/optimize' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/reducer/editable/helper/optimize.test' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/reducer/editable/helper/order' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/reducer/editable/helper/order.test' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/reducer/editable/helper/sizing' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/reducer/editable/helper/sizing.test' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/reducer/editable/helper/tree' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/reducer/editable/index' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/reducer/editable/index.test' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/reducer/editable/tree' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/reducer/editables/index' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/reducer/focus/index' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/reducer/focus/index.test' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/reducer/index' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/reducer/settings/index' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/selector/display/index' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/selector/editable/index' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/selector/editable/index.test' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/selector/focus' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/selector/setting' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/service/hover/index' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/service/hover/index.test' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/service/hover/input' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/service/i18n/index' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/service/index' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/service/logger/index' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/service/plugin/classes' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/service/plugin/default' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/service/plugin/index' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/service/plugin/index.test' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/service/plugin/missing' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/store' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/types/declarations/css-modules' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/types/display' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/types/editable' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/types/hover' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/types/react-dnd' {
  declare module.exports: any;
}

declare module 'ory-editor-core/src/types/redux' {
  declare module.exports: any;
}

declare module 'ory-editor-core/tests/title' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ory-editor-core/flow-typed/npm/classnames_v2.x.x.js' {
  declare module.exports: $Exports<'ory-editor-core/flow-typed/npm/classnames_v2.x.x'>;
}
declare module 'ory-editor-core/flow-typed/npm/deep-equal_vx.x.x.js' {
  declare module.exports: $Exports<'ory-editor-core/flow-typed/npm/deep-equal_vx.x.x'>;
}
declare module 'ory-editor-core/flow-typed/npm/dnd-core_vx.x.x.js' {
  declare module.exports: $Exports<'ory-editor-core/flow-typed/npm/dnd-core_vx.x.x'>;
}
declare module 'ory-editor-core/flow-typed/npm/element-resize-event_vx.x.x.js' {
  declare module.exports: $Exports<'ory-editor-core/flow-typed/npm/element-resize-event_vx.x.x'>;
}
declare module 'ory-editor-core/flow-typed/npm/lodash.throttle_vx.x.x.js' {
  declare module.exports: $Exports<'ory-editor-core/flow-typed/npm/lodash.throttle_vx.x.x'>;
}
declare module 'ory-editor-core/flow-typed/npm/mousetrap_v1.x.x.js' {
  declare module.exports: $Exports<'ory-editor-core/flow-typed/npm/mousetrap_v1.x.x'>;
}
declare module 'ory-editor-core/flow-typed/npm/ramda_v0.x.x.js' {
  declare module.exports: $Exports<'ory-editor-core/flow-typed/npm/ramda_v0.x.x'>;
}
declare module 'ory-editor-core/flow-typed/npm/react-dimensions_vx.x.x.js' {
  declare module.exports: $Exports<'ory-editor-core/flow-typed/npm/react-dimensions_vx.x.x'>;
}
declare module 'ory-editor-core/flow-typed/npm/react-dnd_v2.x.x.js' {
  declare module.exports: $Exports<'ory-editor-core/flow-typed/npm/react-dnd_v2.x.x'>;
}
declare module 'ory-editor-core/flow-typed/npm/react-dnd-html5-backend_v2.1.x.js' {
  declare module.exports: $Exports<'ory-editor-core/flow-typed/npm/react-dnd-html5-backend_v2.1.x'>;
}
declare module 'ory-editor-core/flow-typed/npm/react-draggable_vx.x.x.js' {
  declare module.exports: $Exports<'ory-editor-core/flow-typed/npm/react-draggable_vx.x.x'>;
}
declare module 'ory-editor-core/flow-typed/npm/react-hotkeys_vx.x.x.js' {
  declare module.exports: $Exports<'ory-editor-core/flow-typed/npm/react-hotkeys_vx.x.x'>;
}
declare module 'ory-editor-core/flow-typed/npm/react-redux_v5.x.x.js' {
  declare module.exports: $Exports<'ory-editor-core/flow-typed/npm/react-redux_v5.x.x'>;
}
declare module 'ory-editor-core/flow-typed/npm/redux_v3.x.x.js' {
  declare module.exports: $Exports<'ory-editor-core/flow-typed/npm/redux_v3.x.x'>;
}
declare module 'ory-editor-core/flow-typed/npm/redux-undo_vx.x.x.js' {
  declare module.exports: $Exports<'ory-editor-core/flow-typed/npm/redux-undo_vx.x.x'>;
}
declare module 'ory-editor-core/flow-typed/npm/reselect_v3.x.x.js' {
  declare module.exports: $Exports<'ory-editor-core/flow-typed/npm/reselect_v3.x.x'>;
}
declare module 'ory-editor-core/flow-typed/npm/semver_v5.1.x.js' {
  declare module.exports: $Exports<'ory-editor-core/flow-typed/npm/semver_v5.1.x'>;
}
declare module 'ory-editor-core/flow-typed/npm/uuid_v3.x.x.js' {
  declare module.exports: $Exports<'ory-editor-core/flow-typed/npm/uuid_v3.x.x'>;
}
declare module 'ory-editor-core/src/actions/actions.test.js' {
  declare module.exports: $Exports<'ory-editor-core/src/actions/actions.test'>;
}
declare module 'ory-editor-core/src/actions/cell/core.js' {
  declare module.exports: $Exports<'ory-editor-core/src/actions/cell/core'>;
}
declare module 'ory-editor-core/src/actions/cell/drag.js' {
  declare module.exports: $Exports<'ory-editor-core/src/actions/cell/drag'>;
}
declare module 'ory-editor-core/src/actions/cell/index.js' {
  declare module.exports: $Exports<'ory-editor-core/src/actions/cell/index'>;
}
declare module 'ory-editor-core/src/actions/cell/insert.js' {
  declare module.exports: $Exports<'ory-editor-core/src/actions/cell/insert'>;
}
declare module 'ory-editor-core/src/actions/display.js' {
  declare module.exports: $Exports<'ory-editor-core/src/actions/display'>;
}
declare module 'ory-editor-core/src/actions/editables.js' {
  declare module.exports: $Exports<'ory-editor-core/src/actions/editables'>;
}
declare module 'ory-editor-core/src/actions/helpers.js' {
  declare module.exports: $Exports<'ory-editor-core/src/actions/helpers'>;
}
declare module 'ory-editor-core/src/actions/index.js' {
  declare module.exports: $Exports<'ory-editor-core/src/actions/index'>;
}
declare module 'ory-editor-core/src/actions/setting.js' {
  declare module.exports: $Exports<'ory-editor-core/src/actions/setting'>;
}
declare module 'ory-editor-core/src/actions/undo.js' {
  declare module.exports: $Exports<'ory-editor-core/src/actions/undo'>;
}
declare module 'ory-editor-core/src/components/Cell/Content/index.js' {
  declare module.exports: $Exports<'ory-editor-core/src/components/Cell/Content/index'>;
}
declare module 'ory-editor-core/src/components/Cell/Draggable/helper/dnd.js' {
  declare module.exports: $Exports<'ory-editor-core/src/components/Cell/Draggable/helper/dnd'>;
}
declare module 'ory-editor-core/src/components/Cell/Draggable/index.js' {
  declare module.exports: $Exports<'ory-editor-core/src/components/Cell/Draggable/index'>;
}
declare module 'ory-editor-core/src/components/Cell/Droppable/helper/dnd.js' {
  declare module.exports: $Exports<'ory-editor-core/src/components/Cell/Droppable/helper/dnd'>;
}
declare module 'ory-editor-core/src/components/Cell/Droppable/index.js' {
  declare module.exports: $Exports<'ory-editor-core/src/components/Cell/Droppable/index'>;
}
declare module 'ory-editor-core/src/components/Cell/Empty/index.js' {
  declare module.exports: $Exports<'ory-editor-core/src/components/Cell/Empty/index'>;
}
declare module 'ory-editor-core/src/components/Cell/index.js' {
  declare module.exports: $Exports<'ory-editor-core/src/components/Cell/index'>;
}
declare module 'ory-editor-core/src/components/Cell/Inner/index.js' {
  declare module.exports: $Exports<'ory-editor-core/src/components/Cell/Inner/index'>;
}
declare module 'ory-editor-core/src/components/Cell/Layout/index.js' {
  declare module.exports: $Exports<'ory-editor-core/src/components/Cell/Layout/index'>;
}
declare module 'ory-editor-core/src/components/Cell/Resizable/helper.js' {
  declare module.exports: $Exports<'ory-editor-core/src/components/Cell/Resizable/helper'>;
}
declare module 'ory-editor-core/src/components/Cell/Resizable/index.js' {
  declare module.exports: $Exports<'ory-editor-core/src/components/Cell/Resizable/index'>;
}
declare module 'ory-editor-core/src/components/Cell/Rows/index.js' {
  declare module.exports: $Exports<'ory-editor-core/src/components/Cell/Rows/index'>;
}
declare module 'ory-editor-core/src/components/Cell/Rows/index.test.js' {
  declare module.exports: $Exports<'ory-editor-core/src/components/Cell/Rows/index.test'>;
}
declare module 'ory-editor-core/src/components/Dimensions/index.js' {
  declare module.exports: $Exports<'ory-editor-core/src/components/Dimensions/index'>;
}
declare module 'ory-editor-core/src/components/Dimensions/index.test.js' {
  declare module.exports: $Exports<'ory-editor-core/src/components/Dimensions/index.test'>;
}
declare module 'ory-editor-core/src/components/DragDropContext/index.js' {
  declare module.exports: $Exports<'ory-editor-core/src/components/DragDropContext/index'>;
}
declare module 'ory-editor-core/src/components/DragDropContext/index.test.js' {
  declare module.exports: $Exports<'ory-editor-core/src/components/DragDropContext/index.test'>;
}
declare module 'ory-editor-core/src/components/Editable/index.js' {
  declare module.exports: $Exports<'ory-editor-core/src/components/Editable/index'>;
}
declare module 'ory-editor-core/src/components/Editable/Inner/blur.js' {
  declare module.exports: $Exports<'ory-editor-core/src/components/Editable/Inner/blur'>;
}
declare module 'ory-editor-core/src/components/Editable/Inner/index.js' {
  declare module.exports: $Exports<'ory-editor-core/src/components/Editable/Inner/index'>;
}
declare module 'ory-editor-core/src/components/HotKey/Decorator.js' {
  declare module.exports: $Exports<'ory-editor-core/src/components/HotKey/Decorator'>;
}
declare module 'ory-editor-core/src/components/HotKey/Handler.js' {
  declare module.exports: $Exports<'ory-editor-core/src/components/HotKey/Handler'>;
}
declare module 'ory-editor-core/src/components/Row/Droppable/dnd.js' {
  declare module.exports: $Exports<'ory-editor-core/src/components/Row/Droppable/dnd'>;
}
declare module 'ory-editor-core/src/components/Row/Droppable/index.js' {
  declare module.exports: $Exports<'ory-editor-core/src/components/Row/Droppable/index'>;
}
declare module 'ory-editor-core/src/components/Row/index.js' {
  declare module.exports: $Exports<'ory-editor-core/src/components/Row/index'>;
}
declare module 'ory-editor-core/src/components/Row/inner.js' {
  declare module.exports: $Exports<'ory-editor-core/src/components/Row/inner'>;
}
declare module 'ory-editor-core/src/const.js' {
  declare module.exports: $Exports<'ory-editor-core/src/const'>;
}
declare module 'ory-editor-core/src/helper/dnd/index.js' {
  declare module.exports: $Exports<'ory-editor-core/src/helper/dnd/index'>;
}
declare module 'ory-editor-core/src/helper/shouldComponentUpdate/index.js' {
  declare module.exports: $Exports<'ory-editor-core/src/helper/shouldComponentUpdate/index'>;
}
declare module 'ory-editor-core/src/helper/throttle/index.js' {
  declare module.exports: $Exports<'ory-editor-core/src/helper/throttle/index'>;
}
declare module 'ory-editor-core/src/index.js' {
  declare module.exports: $Exports<'ory-editor-core/src/index'>;
}
declare module 'ory-editor-core/src/index.test.js' {
  declare module.exports: $Exports<'ory-editor-core/src/index.test'>;
}
declare module 'ory-editor-core/src/reducer/display/index.js' {
  declare module.exports: $Exports<'ory-editor-core/src/reducer/display/index'>;
}
declare module 'ory-editor-core/src/reducer/editable/helper/empty.js' {
  declare module.exports: $Exports<'ory-editor-core/src/reducer/editable/helper/empty'>;
}
declare module 'ory-editor-core/src/reducer/editable/helper/empty.test.js' {
  declare module.exports: $Exports<'ory-editor-core/src/reducer/editable/helper/empty.test'>;
}
declare module 'ory-editor-core/src/reducer/editable/helper/hover.js' {
  declare module.exports: $Exports<'ory-editor-core/src/reducer/editable/helper/hover'>;
}
declare module 'ory-editor-core/src/reducer/editable/helper/hover.test.js' {
  declare module.exports: $Exports<'ory-editor-core/src/reducer/editable/helper/hover.test'>;
}
declare module 'ory-editor-core/src/reducer/editable/helper/inline.js' {
  declare module.exports: $Exports<'ory-editor-core/src/reducer/editable/helper/inline'>;
}
declare module 'ory-editor-core/src/reducer/editable/helper/inline.test.js' {
  declare module.exports: $Exports<'ory-editor-core/src/reducer/editable/helper/inline.test'>;
}
declare module 'ory-editor-core/src/reducer/editable/helper/level.js' {
  declare module.exports: $Exports<'ory-editor-core/src/reducer/editable/helper/level'>;
}
declare module 'ory-editor-core/src/reducer/editable/helper/level.test.js' {
  declare module.exports: $Exports<'ory-editor-core/src/reducer/editable/helper/level.test'>;
}
declare module 'ory-editor-core/src/reducer/editable/helper/merge.js' {
  declare module.exports: $Exports<'ory-editor-core/src/reducer/editable/helper/merge'>;
}
declare module 'ory-editor-core/src/reducer/editable/helper/merge.test.js' {
  declare module.exports: $Exports<'ory-editor-core/src/reducer/editable/helper/merge.test'>;
}
declare module 'ory-editor-core/src/reducer/editable/helper/optimize.js' {
  declare module.exports: $Exports<'ory-editor-core/src/reducer/editable/helper/optimize'>;
}
declare module 'ory-editor-core/src/reducer/editable/helper/optimize.test.js' {
  declare module.exports: $Exports<'ory-editor-core/src/reducer/editable/helper/optimize.test'>;
}
declare module 'ory-editor-core/src/reducer/editable/helper/order.js' {
  declare module.exports: $Exports<'ory-editor-core/src/reducer/editable/helper/order'>;
}
declare module 'ory-editor-core/src/reducer/editable/helper/order.test.js' {
  declare module.exports: $Exports<'ory-editor-core/src/reducer/editable/helper/order.test'>;
}
declare module 'ory-editor-core/src/reducer/editable/helper/sizing.js' {
  declare module.exports: $Exports<'ory-editor-core/src/reducer/editable/helper/sizing'>;
}
declare module 'ory-editor-core/src/reducer/editable/helper/sizing.test.js' {
  declare module.exports: $Exports<'ory-editor-core/src/reducer/editable/helper/sizing.test'>;
}
declare module 'ory-editor-core/src/reducer/editable/helper/tree.js' {
  declare module.exports: $Exports<'ory-editor-core/src/reducer/editable/helper/tree'>;
}
declare module 'ory-editor-core/src/reducer/editable/index.js' {
  declare module.exports: $Exports<'ory-editor-core/src/reducer/editable/index'>;
}
declare module 'ory-editor-core/src/reducer/editable/index.test.js' {
  declare module.exports: $Exports<'ory-editor-core/src/reducer/editable/index.test'>;
}
declare module 'ory-editor-core/src/reducer/editable/tree.js' {
  declare module.exports: $Exports<'ory-editor-core/src/reducer/editable/tree'>;
}
declare module 'ory-editor-core/src/reducer/editables/index.js' {
  declare module.exports: $Exports<'ory-editor-core/src/reducer/editables/index'>;
}
declare module 'ory-editor-core/src/reducer/focus/index.js' {
  declare module.exports: $Exports<'ory-editor-core/src/reducer/focus/index'>;
}
declare module 'ory-editor-core/src/reducer/focus/index.test.js' {
  declare module.exports: $Exports<'ory-editor-core/src/reducer/focus/index.test'>;
}
declare module 'ory-editor-core/src/reducer/index.js' {
  declare module.exports: $Exports<'ory-editor-core/src/reducer/index'>;
}
declare module 'ory-editor-core/src/reducer/settings/index.js' {
  declare module.exports: $Exports<'ory-editor-core/src/reducer/settings/index'>;
}
declare module 'ory-editor-core/src/selector/display/index.js' {
  declare module.exports: $Exports<'ory-editor-core/src/selector/display/index'>;
}
declare module 'ory-editor-core/src/selector/editable/index.js' {
  declare module.exports: $Exports<'ory-editor-core/src/selector/editable/index'>;
}
declare module 'ory-editor-core/src/selector/editable/index.test.js' {
  declare module.exports: $Exports<'ory-editor-core/src/selector/editable/index.test'>;
}
declare module 'ory-editor-core/src/selector/focus.js' {
  declare module.exports: $Exports<'ory-editor-core/src/selector/focus'>;
}
declare module 'ory-editor-core/src/selector/setting.js' {
  declare module.exports: $Exports<'ory-editor-core/src/selector/setting'>;
}
declare module 'ory-editor-core/src/service/hover/index.js' {
  declare module.exports: $Exports<'ory-editor-core/src/service/hover/index'>;
}
declare module 'ory-editor-core/src/service/hover/index.test.js' {
  declare module.exports: $Exports<'ory-editor-core/src/service/hover/index.test'>;
}
declare module 'ory-editor-core/src/service/hover/input.js' {
  declare module.exports: $Exports<'ory-editor-core/src/service/hover/input'>;
}
declare module 'ory-editor-core/src/service/i18n/index.js' {
  declare module.exports: $Exports<'ory-editor-core/src/service/i18n/index'>;
}
declare module 'ory-editor-core/src/service/index.js' {
  declare module.exports: $Exports<'ory-editor-core/src/service/index'>;
}
declare module 'ory-editor-core/src/service/logger/index.js' {
  declare module.exports: $Exports<'ory-editor-core/src/service/logger/index'>;
}
declare module 'ory-editor-core/src/service/plugin/classes.js' {
  declare module.exports: $Exports<'ory-editor-core/src/service/plugin/classes'>;
}
declare module 'ory-editor-core/src/service/plugin/default.js' {
  declare module.exports: $Exports<'ory-editor-core/src/service/plugin/default'>;
}
declare module 'ory-editor-core/src/service/plugin/index.js' {
  declare module.exports: $Exports<'ory-editor-core/src/service/plugin/index'>;
}
declare module 'ory-editor-core/src/service/plugin/index.test.js' {
  declare module.exports: $Exports<'ory-editor-core/src/service/plugin/index.test'>;
}
declare module 'ory-editor-core/src/service/plugin/missing.js' {
  declare module.exports: $Exports<'ory-editor-core/src/service/plugin/missing'>;
}
declare module 'ory-editor-core/src/store.js' {
  declare module.exports: $Exports<'ory-editor-core/src/store'>;
}
declare module 'ory-editor-core/src/types/declarations/css-modules.js' {
  declare module.exports: $Exports<'ory-editor-core/src/types/declarations/css-modules'>;
}
declare module 'ory-editor-core/src/types/display.js' {
  declare module.exports: $Exports<'ory-editor-core/src/types/display'>;
}
declare module 'ory-editor-core/src/types/editable.js' {
  declare module.exports: $Exports<'ory-editor-core/src/types/editable'>;
}
declare module 'ory-editor-core/src/types/hover.js' {
  declare module.exports: $Exports<'ory-editor-core/src/types/hover'>;
}
declare module 'ory-editor-core/src/types/react-dnd.js' {
  declare module.exports: $Exports<'ory-editor-core/src/types/react-dnd'>;
}
declare module 'ory-editor-core/src/types/redux.js' {
  declare module.exports: $Exports<'ory-editor-core/src/types/redux'>;
}
declare module 'ory-editor-core/tests/title.js' {
  declare module.exports: $Exports<'ory-editor-core/tests/title'>;
}
