// flow-typed signature: c074a42f4b3cb277466ba2ed098b692a
// flow-typed version: <<STUB>>/ory-editor-plugins-slate_v0.0.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ory-editor-plugins-slate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ory-editor-plugins-slate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ory-editor-plugins-slate/src/Component/index' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-slate/src/const' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-slate/src/helpers' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-slate/src/hooks' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-slate/src/hooks.test' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-slate/src/index' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-slate/src/plugins/alignment' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-slate/src/plugins/blockquote' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-slate/src/plugins/code/index' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-slate/src/plugins/code/node' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-slate/src/plugins/emphasize' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-slate/src/plugins/headings' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-slate/src/plugins/link/index' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-slate/src/plugins/link/node' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-slate/src/plugins/lists' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-slate/src/plugins/paragraph/index' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-slate/src/plugins/paragraph/node' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-slate/src/plugins/Plugin' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-slate/src/plugins/props' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-slate/src/serialize.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ory-editor-plugins-slate/src/Component/index.js' {
  declare module.exports: $Exports<'ory-editor-plugins-slate/src/Component/index'>;
}
declare module 'ory-editor-plugins-slate/src/const.js' {
  declare module.exports: $Exports<'ory-editor-plugins-slate/src/const'>;
}
declare module 'ory-editor-plugins-slate/src/helpers.js' {
  declare module.exports: $Exports<'ory-editor-plugins-slate/src/helpers'>;
}
declare module 'ory-editor-plugins-slate/src/hooks.js' {
  declare module.exports: $Exports<'ory-editor-plugins-slate/src/hooks'>;
}
declare module 'ory-editor-plugins-slate/src/hooks.test.js' {
  declare module.exports: $Exports<'ory-editor-plugins-slate/src/hooks.test'>;
}
declare module 'ory-editor-plugins-slate/src/index.js' {
  declare module.exports: $Exports<'ory-editor-plugins-slate/src/index'>;
}
declare module 'ory-editor-plugins-slate/src/plugins/alignment.js' {
  declare module.exports: $Exports<'ory-editor-plugins-slate/src/plugins/alignment'>;
}
declare module 'ory-editor-plugins-slate/src/plugins/blockquote.js' {
  declare module.exports: $Exports<'ory-editor-plugins-slate/src/plugins/blockquote'>;
}
declare module 'ory-editor-plugins-slate/src/plugins/code/index.js' {
  declare module.exports: $Exports<'ory-editor-plugins-slate/src/plugins/code/index'>;
}
declare module 'ory-editor-plugins-slate/src/plugins/code/node.js' {
  declare module.exports: $Exports<'ory-editor-plugins-slate/src/plugins/code/node'>;
}
declare module 'ory-editor-plugins-slate/src/plugins/emphasize.js' {
  declare module.exports: $Exports<'ory-editor-plugins-slate/src/plugins/emphasize'>;
}
declare module 'ory-editor-plugins-slate/src/plugins/headings.js' {
  declare module.exports: $Exports<'ory-editor-plugins-slate/src/plugins/headings'>;
}
declare module 'ory-editor-plugins-slate/src/plugins/link/index.js' {
  declare module.exports: $Exports<'ory-editor-plugins-slate/src/plugins/link/index'>;
}
declare module 'ory-editor-plugins-slate/src/plugins/link/node.js' {
  declare module.exports: $Exports<'ory-editor-plugins-slate/src/plugins/link/node'>;
}
declare module 'ory-editor-plugins-slate/src/plugins/lists.js' {
  declare module.exports: $Exports<'ory-editor-plugins-slate/src/plugins/lists'>;
}
declare module 'ory-editor-plugins-slate/src/plugins/paragraph/index.js' {
  declare module.exports: $Exports<'ory-editor-plugins-slate/src/plugins/paragraph/index'>;
}
declare module 'ory-editor-plugins-slate/src/plugins/paragraph/node.js' {
  declare module.exports: $Exports<'ory-editor-plugins-slate/src/plugins/paragraph/node'>;
}
declare module 'ory-editor-plugins-slate/src/plugins/Plugin.js' {
  declare module.exports: $Exports<'ory-editor-plugins-slate/src/plugins/Plugin'>;
}
declare module 'ory-editor-plugins-slate/src/plugins/props.js' {
  declare module.exports: $Exports<'ory-editor-plugins-slate/src/plugins/props'>;
}
declare module 'ory-editor-plugins-slate/src/serialize.test.js' {
  declare module.exports: $Exports<'ory-editor-plugins-slate/src/serialize.test'>;
}
