// flow-typed signature: 7535daae387227171871a17f46dd5ba3
// flow-typed version: <<STUB>>/parse5_v^3.0.2/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'parse5'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'parse5' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'parse5/lib/common/doctype' {
  declare module.exports: any;
}

declare module 'parse5/lib/common/foreign_content' {
  declare module.exports: any;
}

declare module 'parse5/lib/common/html' {
  declare module.exports: any;
}

declare module 'parse5/lib/common/unicode' {
  declare module.exports: any;
}

declare module 'parse5/lib/extensions/location_info/open_element_stack_mixin' {
  declare module.exports: any;
}

declare module 'parse5/lib/extensions/location_info/parser_mixin' {
  declare module.exports: any;
}

declare module 'parse5/lib/extensions/location_info/tokenizer_mixin' {
  declare module.exports: any;
}

declare module 'parse5/lib/extensions/position_tracking/preprocessor_mixin' {
  declare module.exports: any;
}

declare module 'parse5/lib/index' {
  declare module.exports: any;
}

declare module 'parse5/lib/parser/formatting_element_list' {
  declare module.exports: any;
}

declare module 'parse5/lib/parser/index' {
  declare module.exports: any;
}

declare module 'parse5/lib/parser/open_element_stack' {
  declare module.exports: any;
}

declare module 'parse5/lib/parser/parser_stream' {
  declare module.exports: any;
}

declare module 'parse5/lib/parser/plain_text_conversion_stream' {
  declare module.exports: any;
}

declare module 'parse5/lib/sax/dev_null_stream' {
  declare module.exports: any;
}

declare module 'parse5/lib/sax/index' {
  declare module.exports: any;
}

declare module 'parse5/lib/sax/parser_feedback_simulator' {
  declare module.exports: any;
}

declare module 'parse5/lib/serializer/index' {
  declare module.exports: any;
}

declare module 'parse5/lib/serializer/serializer_stream' {
  declare module.exports: any;
}

declare module 'parse5/lib/tokenizer/index' {
  declare module.exports: any;
}

declare module 'parse5/lib/tokenizer/named_entity_data' {
  declare module.exports: any;
}

declare module 'parse5/lib/tokenizer/preprocessor' {
  declare module.exports: any;
}

declare module 'parse5/lib/tree_adapters/default' {
  declare module.exports: any;
}

declare module 'parse5/lib/tree_adapters/htmlparser2' {
  declare module.exports: any;
}

declare module 'parse5/lib/utils/merge_options' {
  declare module.exports: any;
}

declare module 'parse5/lib/utils/mixin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'parse5/lib/common/doctype.js' {
  declare module.exports: $Exports<'parse5/lib/common/doctype'>;
}
declare module 'parse5/lib/common/foreign_content.js' {
  declare module.exports: $Exports<'parse5/lib/common/foreign_content'>;
}
declare module 'parse5/lib/common/html.js' {
  declare module.exports: $Exports<'parse5/lib/common/html'>;
}
declare module 'parse5/lib/common/unicode.js' {
  declare module.exports: $Exports<'parse5/lib/common/unicode'>;
}
declare module 'parse5/lib/extensions/location_info/open_element_stack_mixin.js' {
  declare module.exports: $Exports<'parse5/lib/extensions/location_info/open_element_stack_mixin'>;
}
declare module 'parse5/lib/extensions/location_info/parser_mixin.js' {
  declare module.exports: $Exports<'parse5/lib/extensions/location_info/parser_mixin'>;
}
declare module 'parse5/lib/extensions/location_info/tokenizer_mixin.js' {
  declare module.exports: $Exports<'parse5/lib/extensions/location_info/tokenizer_mixin'>;
}
declare module 'parse5/lib/extensions/position_tracking/preprocessor_mixin.js' {
  declare module.exports: $Exports<'parse5/lib/extensions/position_tracking/preprocessor_mixin'>;
}
declare module 'parse5/lib/index.js' {
  declare module.exports: $Exports<'parse5/lib/index'>;
}
declare module 'parse5/lib/parser/formatting_element_list.js' {
  declare module.exports: $Exports<'parse5/lib/parser/formatting_element_list'>;
}
declare module 'parse5/lib/parser/index.js' {
  declare module.exports: $Exports<'parse5/lib/parser/index'>;
}
declare module 'parse5/lib/parser/open_element_stack.js' {
  declare module.exports: $Exports<'parse5/lib/parser/open_element_stack'>;
}
declare module 'parse5/lib/parser/parser_stream.js' {
  declare module.exports: $Exports<'parse5/lib/parser/parser_stream'>;
}
declare module 'parse5/lib/parser/plain_text_conversion_stream.js' {
  declare module.exports: $Exports<'parse5/lib/parser/plain_text_conversion_stream'>;
}
declare module 'parse5/lib/sax/dev_null_stream.js' {
  declare module.exports: $Exports<'parse5/lib/sax/dev_null_stream'>;
}
declare module 'parse5/lib/sax/index.js' {
  declare module.exports: $Exports<'parse5/lib/sax/index'>;
}
declare module 'parse5/lib/sax/parser_feedback_simulator.js' {
  declare module.exports: $Exports<'parse5/lib/sax/parser_feedback_simulator'>;
}
declare module 'parse5/lib/serializer/index.js' {
  declare module.exports: $Exports<'parse5/lib/serializer/index'>;
}
declare module 'parse5/lib/serializer/serializer_stream.js' {
  declare module.exports: $Exports<'parse5/lib/serializer/serializer_stream'>;
}
declare module 'parse5/lib/tokenizer/index.js' {
  declare module.exports: $Exports<'parse5/lib/tokenizer/index'>;
}
declare module 'parse5/lib/tokenizer/named_entity_data.js' {
  declare module.exports: $Exports<'parse5/lib/tokenizer/named_entity_data'>;
}
declare module 'parse5/lib/tokenizer/preprocessor.js' {
  declare module.exports: $Exports<'parse5/lib/tokenizer/preprocessor'>;
}
declare module 'parse5/lib/tree_adapters/default.js' {
  declare module.exports: $Exports<'parse5/lib/tree_adapters/default'>;
}
declare module 'parse5/lib/tree_adapters/htmlparser2.js' {
  declare module.exports: $Exports<'parse5/lib/tree_adapters/htmlparser2'>;
}
declare module 'parse5/lib/utils/merge_options.js' {
  declare module.exports: $Exports<'parse5/lib/utils/merge_options'>;
}
declare module 'parse5/lib/utils/mixin.js' {
  declare module.exports: $Exports<'parse5/lib/utils/mixin'>;
}
