// flow-typed signature: d0e78f2798a33ae47931c5d279e222fb
// flow-typed version: <<STUB>>/postcss-nested_v^2.0.2/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-nested'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-nested' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-nested/index' {
  declare module.exports: $Exports<'postcss-nested'>;
}
declare module 'postcss-nested/index.js' {
  declare module.exports: $Exports<'postcss-nested'>;
}
