// flow-typed signature: 388018ec11441e7d93d2c7766cbbb3f7
// flow-typed version: <<STUB>>/pushstate-server_v^3.0.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pushstate-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pushstate-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'pushstate-server/index' {
  declare module.exports: $Exports<'pushstate-server'>;
}
declare module 'pushstate-server/index.js' {
  declare module.exports: $Exports<'pushstate-server'>;
}
