// flow-typed signature: 293dd25c22b1675087a9261334bbd092
// flow-typed version: <<STUB>>/rc-tooltip_v^3.4.3/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rc-tooltip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rc-tooltip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rc-tooltip/dist/rc-tooltip' {
  declare module.exports: any;
}

declare module 'rc-tooltip/dist/rc-tooltip.min' {
  declare module.exports: any;
}

declare module 'rc-tooltip/es/Content' {
  declare module.exports: any;
}

declare module 'rc-tooltip/es/index' {
  declare module.exports: any;
}

declare module 'rc-tooltip/es/placements' {
  declare module.exports: any;
}

declare module 'rc-tooltip/es/Tooltip' {
  declare module.exports: any;
}

declare module 'rc-tooltip/lib/Content' {
  declare module.exports: any;
}

declare module 'rc-tooltip/lib/index' {
  declare module.exports: any;
}

declare module 'rc-tooltip/lib/placements' {
  declare module.exports: any;
}

declare module 'rc-tooltip/lib/Tooltip' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rc-tooltip/dist/rc-tooltip.js' {
  declare module.exports: $Exports<'rc-tooltip/dist/rc-tooltip'>;
}
declare module 'rc-tooltip/dist/rc-tooltip.min.js' {
  declare module.exports: $Exports<'rc-tooltip/dist/rc-tooltip.min'>;
}
declare module 'rc-tooltip/es/Content.js' {
  declare module.exports: $Exports<'rc-tooltip/es/Content'>;
}
declare module 'rc-tooltip/es/index.js' {
  declare module.exports: $Exports<'rc-tooltip/es/index'>;
}
declare module 'rc-tooltip/es/placements.js' {
  declare module.exports: $Exports<'rc-tooltip/es/placements'>;
}
declare module 'rc-tooltip/es/Tooltip.js' {
  declare module.exports: $Exports<'rc-tooltip/es/Tooltip'>;
}
declare module 'rc-tooltip/lib/Content.js' {
  declare module.exports: $Exports<'rc-tooltip/lib/Content'>;
}
declare module 'rc-tooltip/lib/index.js' {
  declare module.exports: $Exports<'rc-tooltip/lib/index'>;
}
declare module 'rc-tooltip/lib/placements.js' {
  declare module.exports: $Exports<'rc-tooltip/lib/placements'>;
}
declare module 'rc-tooltip/lib/Tooltip.js' {
  declare module.exports: $Exports<'rc-tooltip/lib/Tooltip'>;
}
