// flow-typed signature: b82539a86e97043f81cf93f8d3eb58f5
// flow-typed version: <<STUB>>/react-player_v^0.22.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-player'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-player' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-player/dist/ReactPlayer' {
  declare module.exports: any;
}

declare module 'react-player/lib/players/Base' {
  declare module.exports: any;
}

declare module 'react-player/lib/players/DailyMotion' {
  declare module.exports: any;
}

declare module 'react-player/lib/players/Facebook' {
  declare module.exports: any;
}

declare module 'react-player/lib/players/FilePlayer' {
  declare module.exports: any;
}

declare module 'react-player/lib/players/SoundCloud' {
  declare module.exports: any;
}

declare module 'react-player/lib/players/Streamable' {
  declare module.exports: any;
}

declare module 'react-player/lib/players/Twitch' {
  declare module.exports: any;
}

declare module 'react-player/lib/players/Vidme' {
  declare module.exports: any;
}

declare module 'react-player/lib/players/Vimeo' {
  declare module.exports: any;
}

declare module 'react-player/lib/players/Wistia' {
  declare module.exports: any;
}

declare module 'react-player/lib/players/YouTube' {
  declare module.exports: any;
}

declare module 'react-player/lib/props' {
  declare module.exports: any;
}

declare module 'react-player/lib/ReactPlayer' {
  declare module.exports: any;
}

declare module 'react-player/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-player/dist/ReactPlayer.js' {
  declare module.exports: $Exports<'react-player/dist/ReactPlayer'>;
}
declare module 'react-player/lib/players/Base.js' {
  declare module.exports: $Exports<'react-player/lib/players/Base'>;
}
declare module 'react-player/lib/players/DailyMotion.js' {
  declare module.exports: $Exports<'react-player/lib/players/DailyMotion'>;
}
declare module 'react-player/lib/players/Facebook.js' {
  declare module.exports: $Exports<'react-player/lib/players/Facebook'>;
}
declare module 'react-player/lib/players/FilePlayer.js' {
  declare module.exports: $Exports<'react-player/lib/players/FilePlayer'>;
}
declare module 'react-player/lib/players/SoundCloud.js' {
  declare module.exports: $Exports<'react-player/lib/players/SoundCloud'>;
}
declare module 'react-player/lib/players/Streamable.js' {
  declare module.exports: $Exports<'react-player/lib/players/Streamable'>;
}
declare module 'react-player/lib/players/Twitch.js' {
  declare module.exports: $Exports<'react-player/lib/players/Twitch'>;
}
declare module 'react-player/lib/players/Vidme.js' {
  declare module.exports: $Exports<'react-player/lib/players/Vidme'>;
}
declare module 'react-player/lib/players/Vimeo.js' {
  declare module.exports: $Exports<'react-player/lib/players/Vimeo'>;
}
declare module 'react-player/lib/players/Wistia.js' {
  declare module.exports: $Exports<'react-player/lib/players/Wistia'>;
}
declare module 'react-player/lib/players/YouTube.js' {
  declare module.exports: $Exports<'react-player/lib/players/YouTube'>;
}
declare module 'react-player/lib/props.js' {
  declare module.exports: $Exports<'react-player/lib/props'>;
}
declare module 'react-player/lib/ReactPlayer.js' {
  declare module.exports: $Exports<'react-player/lib/ReactPlayer'>;
}
declare module 'react-player/lib/utils.js' {
  declare module.exports: $Exports<'react-player/lib/utils'>;
}
