// flow-typed signature: 68ce15c2b4c8948ff9771379e557f88b
// flow-typed version: <<STUB>>/react-hotkeys_v^0.10.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-hotkeys'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-hotkeys' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-hotkeys/lib/FocusTrap' {
  declare module.exports: any;
}

declare module 'react-hotkeys/lib/FocusTrapHOC' {
  declare module.exports: any;
}

declare module 'react-hotkeys/lib/HotKeyMapMixin' {
  declare module.exports: any;
}

declare module 'react-hotkeys/lib/HotKeys' {
  declare module.exports: any;
}

declare module 'react-hotkeys/lib/HotKeysHOC' {
  declare module.exports: any;
}

declare module 'react-hotkeys/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-hotkeys/lib/FocusTrap.js' {
  declare module.exports: $Exports<'react-hotkeys/lib/FocusTrap'>;
}
declare module 'react-hotkeys/lib/FocusTrapHOC.js' {
  declare module.exports: $Exports<'react-hotkeys/lib/FocusTrapHOC'>;
}
declare module 'react-hotkeys/lib/HotKeyMapMixin.js' {
  declare module.exports: $Exports<'react-hotkeys/lib/HotKeyMapMixin'>;
}
declare module 'react-hotkeys/lib/HotKeys.js' {
  declare module.exports: $Exports<'react-hotkeys/lib/HotKeys'>;
}
declare module 'react-hotkeys/lib/HotKeysHOC.js' {
  declare module.exports: $Exports<'react-hotkeys/lib/HotKeysHOC'>;
}
declare module 'react-hotkeys/lib/index.js' {
  declare module.exports: $Exports<'react-hotkeys/lib/index'>;
}
