// flow-typed signature: cb9cb68742533f88eca79b7181485622
// flow-typed version: <<STUB>>/react-portal_v4.1.5/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-portal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-portal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-portal/es/index' {
  declare module.exports: any;
}

declare module 'react-portal/es/LegacyPortal' {
  declare module.exports: any;
}

declare module 'react-portal/es/Portal' {
  declare module.exports: any;
}

declare module 'react-portal/es/PortalCompat' {
  declare module.exports: any;
}

declare module 'react-portal/es/PortalWithState' {
  declare module.exports: any;
}

declare module 'react-portal/es/utils' {
  declare module.exports: any;
}

declare module 'react-portal/lib/index' {
  declare module.exports: any;
}

declare module 'react-portal/lib/LegacyPortal' {
  declare module.exports: any;
}

declare module 'react-portal/lib/Portal' {
  declare module.exports: any;
}

declare module 'react-portal/lib/PortalCompat' {
  declare module.exports: any;
}

declare module 'react-portal/lib/PortalWithState' {
  declare module.exports: any;
}

declare module 'react-portal/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-portal/es/index.js' {
  declare module.exports: $Exports<'react-portal/es/index'>;
}
declare module 'react-portal/es/LegacyPortal.js' {
  declare module.exports: $Exports<'react-portal/es/LegacyPortal'>;
}
declare module 'react-portal/es/Portal.js' {
  declare module.exports: $Exports<'react-portal/es/Portal'>;
}
declare module 'react-portal/es/PortalCompat.js' {
  declare module.exports: $Exports<'react-portal/es/PortalCompat'>;
}
declare module 'react-portal/es/PortalWithState.js' {
  declare module.exports: $Exports<'react-portal/es/PortalWithState'>;
}
declare module 'react-portal/es/utils.js' {
  declare module.exports: $Exports<'react-portal/es/utils'>;
}
declare module 'react-portal/lib/index.js' {
  declare module.exports: $Exports<'react-portal/lib/index'>;
}
declare module 'react-portal/lib/LegacyPortal.js' {
  declare module.exports: $Exports<'react-portal/lib/LegacyPortal'>;
}
declare module 'react-portal/lib/Portal.js' {
  declare module.exports: $Exports<'react-portal/lib/Portal'>;
}
declare module 'react-portal/lib/PortalCompat.js' {
  declare module.exports: $Exports<'react-portal/lib/PortalCompat'>;
}
declare module 'react-portal/lib/PortalWithState.js' {
  declare module.exports: $Exports<'react-portal/lib/PortalWithState'>;
}
declare module 'react-portal/lib/utils.js' {
  declare module.exports: $Exports<'react-portal/lib/utils'>;
}
