// flow-typed signature: 45fe31c19a87cc911e5d625abad9e37f
// flow-typed version: <<STUB>>/react-draggable_v^2.2.6/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-draggable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-draggable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-draggable/dist/react-draggable' {
  declare module.exports: any;
}

declare module 'react-draggable/dist/react-draggable.min' {
  declare module.exports: any;
}

declare module 'react-draggable/interfaces/dom' {
  declare module.exports: any;
}

declare module 'react-draggable/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-draggable/dist/react-draggable.js' {
  declare module.exports: $Exports<'react-draggable/dist/react-draggable'>;
}
declare module 'react-draggable/dist/react-draggable.min.js' {
  declare module.exports: $Exports<'react-draggable/dist/react-draggable.min'>;
}
declare module 'react-draggable/index' {
  declare module.exports: $Exports<'react-draggable'>;
}
declare module 'react-draggable/index.js' {
  declare module.exports: $Exports<'react-draggable'>;
}
declare module 'react-draggable/interfaces/dom.js' {
  declare module.exports: $Exports<'react-draggable/interfaces/dom'>;
}
declare module 'react-draggable/webpack.config.js' {
  declare module.exports: $Exports<'react-draggable/webpack.config'>;
}
