// flow-typed signature: ab52a249d5c2729cbb67aaa3d1782d2f
// flow-typed version: <<STUB>>/redux-undo_v1.0.0-beta9-7/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-undo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-undo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-undo/dist/redux-undo' {
  declare module.exports: any;
}

declare module 'redux-undo/es/actions' {
  declare module.exports: any;
}

declare module 'redux-undo/es/debug' {
  declare module.exports: any;
}

declare module 'redux-undo/es/helpers' {
  declare module.exports: any;
}

declare module 'redux-undo/es/index' {
  declare module.exports: any;
}

declare module 'redux-undo/es/reducer' {
  declare module.exports: any;
}

declare module 'redux-undo/examples/throttled-drag/actions/index' {
  declare module.exports: any;
}

declare module 'redux-undo/examples/throttled-drag/components/Draggable' {
  declare module.exports: any;
}

declare module 'redux-undo/examples/throttled-drag/index' {
  declare module.exports: any;
}

declare module 'redux-undo/examples/throttled-drag/reducers/draggable' {
  declare module.exports: any;
}

declare module 'redux-undo/examples/throttled-drag/reducers/index' {
  declare module.exports: any;
}

declare module 'redux-undo/examples/throttled-drag/server' {
  declare module.exports: any;
}

declare module 'redux-undo/examples/throttled-drag/util/undoFilter' {
  declare module.exports: any;
}

declare module 'redux-undo/examples/throttled-drag/webpack.config' {
  declare module.exports: any;
}

declare module 'redux-undo/examples/todos-with-undo/actions/index' {
  declare module.exports: any;
}

declare module 'redux-undo/examples/todos-with-undo/components/App' {
  declare module.exports: any;
}

declare module 'redux-undo/examples/todos-with-undo/components/Footer' {
  declare module.exports: any;
}

declare module 'redux-undo/examples/todos-with-undo/components/Link' {
  declare module.exports: any;
}

declare module 'redux-undo/examples/todos-with-undo/components/Todo' {
  declare module.exports: any;
}

declare module 'redux-undo/examples/todos-with-undo/components/TodoList' {
  declare module.exports: any;
}

declare module 'redux-undo/examples/todos-with-undo/containers/AddTodo' {
  declare module.exports: any;
}

declare module 'redux-undo/examples/todos-with-undo/containers/FilterLink' {
  declare module.exports: any;
}

declare module 'redux-undo/examples/todos-with-undo/containers/UndoRedo' {
  declare module.exports: any;
}

declare module 'redux-undo/examples/todos-with-undo/containers/VisibleTodoList' {
  declare module.exports: any;
}

declare module 'redux-undo/examples/todos-with-undo/index' {
  declare module.exports: any;
}

declare module 'redux-undo/examples/todos-with-undo/reducers/index' {
  declare module.exports: any;
}

declare module 'redux-undo/examples/todos-with-undo/reducers/todos' {
  declare module.exports: any;
}

declare module 'redux-undo/examples/todos-with-undo/reducers/visibilityFilter' {
  declare module.exports: any;
}

declare module 'redux-undo/examples/todos-with-undo/server' {
  declare module.exports: any;
}

declare module 'redux-undo/examples/todos-with-undo/webpack.config' {
  declare module.exports: any;
}

declare module 'redux-undo/lib/actions' {
  declare module.exports: any;
}

declare module 'redux-undo/lib/debug' {
  declare module.exports: any;
}

declare module 'redux-undo/lib/helpers' {
  declare module.exports: any;
}

declare module 'redux-undo/lib/index' {
  declare module.exports: any;
}

declare module 'redux-undo/lib/reducer' {
  declare module.exports: any;
}

declare module 'redux-undo/webpack.config.babel' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-undo/dist/redux-undo.js' {
  declare module.exports: $Exports<'redux-undo/dist/redux-undo'>;
}
declare module 'redux-undo/es/actions.js' {
  declare module.exports: $Exports<'redux-undo/es/actions'>;
}
declare module 'redux-undo/es/debug.js' {
  declare module.exports: $Exports<'redux-undo/es/debug'>;
}
declare module 'redux-undo/es/helpers.js' {
  declare module.exports: $Exports<'redux-undo/es/helpers'>;
}
declare module 'redux-undo/es/index.js' {
  declare module.exports: $Exports<'redux-undo/es/index'>;
}
declare module 'redux-undo/es/reducer.js' {
  declare module.exports: $Exports<'redux-undo/es/reducer'>;
}
declare module 'redux-undo/examples/throttled-drag/actions/index.js' {
  declare module.exports: $Exports<'redux-undo/examples/throttled-drag/actions/index'>;
}
declare module 'redux-undo/examples/throttled-drag/components/Draggable.js' {
  declare module.exports: $Exports<'redux-undo/examples/throttled-drag/components/Draggable'>;
}
declare module 'redux-undo/examples/throttled-drag/index.js' {
  declare module.exports: $Exports<'redux-undo/examples/throttled-drag/index'>;
}
declare module 'redux-undo/examples/throttled-drag/reducers/draggable.js' {
  declare module.exports: $Exports<'redux-undo/examples/throttled-drag/reducers/draggable'>;
}
declare module 'redux-undo/examples/throttled-drag/reducers/index.js' {
  declare module.exports: $Exports<'redux-undo/examples/throttled-drag/reducers/index'>;
}
declare module 'redux-undo/examples/throttled-drag/server.js' {
  declare module.exports: $Exports<'redux-undo/examples/throttled-drag/server'>;
}
declare module 'redux-undo/examples/throttled-drag/util/undoFilter.js' {
  declare module.exports: $Exports<'redux-undo/examples/throttled-drag/util/undoFilter'>;
}
declare module 'redux-undo/examples/throttled-drag/webpack.config.js' {
  declare module.exports: $Exports<'redux-undo/examples/throttled-drag/webpack.config'>;
}
declare module 'redux-undo/examples/todos-with-undo/actions/index.js' {
  declare module.exports: $Exports<'redux-undo/examples/todos-with-undo/actions/index'>;
}
declare module 'redux-undo/examples/todos-with-undo/components/App.js' {
  declare module.exports: $Exports<'redux-undo/examples/todos-with-undo/components/App'>;
}
declare module 'redux-undo/examples/todos-with-undo/components/Footer.js' {
  declare module.exports: $Exports<'redux-undo/examples/todos-with-undo/components/Footer'>;
}
declare module 'redux-undo/examples/todos-with-undo/components/Link.js' {
  declare module.exports: $Exports<'redux-undo/examples/todos-with-undo/components/Link'>;
}
declare module 'redux-undo/examples/todos-with-undo/components/Todo.js' {
  declare module.exports: $Exports<'redux-undo/examples/todos-with-undo/components/Todo'>;
}
declare module 'redux-undo/examples/todos-with-undo/components/TodoList.js' {
  declare module.exports: $Exports<'redux-undo/examples/todos-with-undo/components/TodoList'>;
}
declare module 'redux-undo/examples/todos-with-undo/containers/AddTodo.js' {
  declare module.exports: $Exports<'redux-undo/examples/todos-with-undo/containers/AddTodo'>;
}
declare module 'redux-undo/examples/todos-with-undo/containers/FilterLink.js' {
  declare module.exports: $Exports<'redux-undo/examples/todos-with-undo/containers/FilterLink'>;
}
declare module 'redux-undo/examples/todos-with-undo/containers/UndoRedo.js' {
  declare module.exports: $Exports<'redux-undo/examples/todos-with-undo/containers/UndoRedo'>;
}
declare module 'redux-undo/examples/todos-with-undo/containers/VisibleTodoList.js' {
  declare module.exports: $Exports<'redux-undo/examples/todos-with-undo/containers/VisibleTodoList'>;
}
declare module 'redux-undo/examples/todos-with-undo/index.js' {
  declare module.exports: $Exports<'redux-undo/examples/todos-with-undo/index'>;
}
declare module 'redux-undo/examples/todos-with-undo/reducers/index.js' {
  declare module.exports: $Exports<'redux-undo/examples/todos-with-undo/reducers/index'>;
}
declare module 'redux-undo/examples/todos-with-undo/reducers/todos.js' {
  declare module.exports: $Exports<'redux-undo/examples/todos-with-undo/reducers/todos'>;
}
declare module 'redux-undo/examples/todos-with-undo/reducers/visibilityFilter.js' {
  declare module.exports: $Exports<'redux-undo/examples/todos-with-undo/reducers/visibilityFilter'>;
}
declare module 'redux-undo/examples/todos-with-undo/server.js' {
  declare module.exports: $Exports<'redux-undo/examples/todos-with-undo/server'>;
}
declare module 'redux-undo/examples/todos-with-undo/webpack.config.js' {
  declare module.exports: $Exports<'redux-undo/examples/todos-with-undo/webpack.config'>;
}
declare module 'redux-undo/lib/actions.js' {
  declare module.exports: $Exports<'redux-undo/lib/actions'>;
}
declare module 'redux-undo/lib/debug.js' {
  declare module.exports: $Exports<'redux-undo/lib/debug'>;
}
declare module 'redux-undo/lib/helpers.js' {
  declare module.exports: $Exports<'redux-undo/lib/helpers'>;
}
declare module 'redux-undo/lib/index.js' {
  declare module.exports: $Exports<'redux-undo/lib/index'>;
}
declare module 'redux-undo/lib/reducer.js' {
  declare module.exports: $Exports<'redux-undo/lib/reducer'>;
}
declare module 'redux-undo/webpack.config.babel.js' {
  declare module.exports: $Exports<'redux-undo/webpack.config.babel'>;
}
