// flow-typed signature: e32a2f6a918574259f4384ae31b9e498
// flow-typed version: <<STUB>>/selection-position_v^1.0.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'selection-position'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'selection-position' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'selection-position/test/selection-position' {
  declare module.exports: any;
}

// Filename aliases
declare module 'selection-position/index' {
  declare module.exports: $Exports<'selection-position'>;
}
declare module 'selection-position/index.js' {
  declare module.exports: $Exports<'selection-position'>;
}
declare module 'selection-position/test/selection-position.js' {
  declare module.exports: $Exports<'selection-position/test/selection-position'>;
}
