// flow-typed signature: 6f1c18511216e85c82a77288367bc37e
// flow-typed version: <<STUB>>/slate-html-serializer_v0.6.21/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'slate-html-serializer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'slate-html-serializer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'slate-html-serializer/dist/slate-html-serializer' {
  declare module.exports: any;
}

declare module 'slate-html-serializer/dist/slate-html-serializer.min' {
  declare module.exports: any;
}

declare module 'slate-html-serializer/lib/slate-html-serializer.es' {
  declare module.exports: any;
}

declare module 'slate-html-serializer/lib/slate-html-serializer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'slate-html-serializer/dist/slate-html-serializer.js' {
  declare module.exports: $Exports<'slate-html-serializer/dist/slate-html-serializer'>;
}
declare module 'slate-html-serializer/dist/slate-html-serializer.min.js' {
  declare module.exports: $Exports<'slate-html-serializer/dist/slate-html-serializer.min'>;
}
declare module 'slate-html-serializer/lib/slate-html-serializer.es.js' {
  declare module.exports: $Exports<'slate-html-serializer/lib/slate-html-serializer.es'>;
}
declare module 'slate-html-serializer/lib/slate-html-serializer.js' {
  declare module.exports: $Exports<'slate-html-serializer/lib/slate-html-serializer'>;
}
