// flow-typed signature: 16d819e6d5af9c0d75b9e4584d020e65
// flow-typed version: <<STUB>>/slate-edit-blockquote_v^0.2.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'slate-edit-blockquote'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'slate-edit-blockquote' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'slate-edit-blockquote/dist/getCurrentBlockquote' {
  declare module.exports: any;
}

declare module 'slate-edit-blockquote/dist/index' {
  declare module.exports: any;
}

declare module 'slate-edit-blockquote/dist/makeSchema' {
  declare module.exports: any;
}

declare module 'slate-edit-blockquote/dist/onBackspace' {
  declare module.exports: any;
}

declare module 'slate-edit-blockquote/dist/onEnter' {
  declare module.exports: any;
}

declare module 'slate-edit-blockquote/dist/onTab' {
  declare module.exports: any;
}

declare module 'slate-edit-blockquote/dist/transforms/unwrapBlockquote' {
  declare module.exports: any;
}

declare module 'slate-edit-blockquote/dist/transforms/wrapInBlockquote' {
  declare module.exports: any;
}

declare module 'slate-edit-blockquote/example/bundle' {
  declare module.exports: any;
}

declare module 'slate-edit-blockquote/example/main' {
  declare module.exports: any;
}

declare module 'slate-edit-blockquote/tests/all' {
  declare module.exports: any;
}

declare module 'slate-edit-blockquote/tests/backspace-deep-block/transform' {
  declare module.exports: any;
}

declare module 'slate-edit-blockquote/tests/backspace-start-block/transform' {
  declare module.exports: any;
}

declare module 'slate-edit-blockquote/tests/enter-empty-middle/transform' {
  declare module.exports: any;
}

declare module 'slate-edit-blockquote/tests/enter-withtext-middle/transform' {
  declare module.exports: any;
}

declare module 'slate-edit-blockquote/tests/schema-items-contain-blocks/transform' {
  declare module.exports: any;
}

// Filename aliases
declare module 'slate-edit-blockquote/dist/getCurrentBlockquote.js' {
  declare module.exports: $Exports<'slate-edit-blockquote/dist/getCurrentBlockquote'>;
}
declare module 'slate-edit-blockquote/dist/index.js' {
  declare module.exports: $Exports<'slate-edit-blockquote/dist/index'>;
}
declare module 'slate-edit-blockquote/dist/makeSchema.js' {
  declare module.exports: $Exports<'slate-edit-blockquote/dist/makeSchema'>;
}
declare module 'slate-edit-blockquote/dist/onBackspace.js' {
  declare module.exports: $Exports<'slate-edit-blockquote/dist/onBackspace'>;
}
declare module 'slate-edit-blockquote/dist/onEnter.js' {
  declare module.exports: $Exports<'slate-edit-blockquote/dist/onEnter'>;
}
declare module 'slate-edit-blockquote/dist/onTab.js' {
  declare module.exports: $Exports<'slate-edit-blockquote/dist/onTab'>;
}
declare module 'slate-edit-blockquote/dist/transforms/unwrapBlockquote.js' {
  declare module.exports: $Exports<'slate-edit-blockquote/dist/transforms/unwrapBlockquote'>;
}
declare module 'slate-edit-blockquote/dist/transforms/wrapInBlockquote.js' {
  declare module.exports: $Exports<'slate-edit-blockquote/dist/transforms/wrapInBlockquote'>;
}
declare module 'slate-edit-blockquote/example/bundle.js' {
  declare module.exports: $Exports<'slate-edit-blockquote/example/bundle'>;
}
declare module 'slate-edit-blockquote/example/main.js' {
  declare module.exports: $Exports<'slate-edit-blockquote/example/main'>;
}
declare module 'slate-edit-blockquote/tests/all.js' {
  declare module.exports: $Exports<'slate-edit-blockquote/tests/all'>;
}
declare module 'slate-edit-blockquote/tests/backspace-deep-block/transform.js' {
  declare module.exports: $Exports<'slate-edit-blockquote/tests/backspace-deep-block/transform'>;
}
declare module 'slate-edit-blockquote/tests/backspace-start-block/transform.js' {
  declare module.exports: $Exports<'slate-edit-blockquote/tests/backspace-start-block/transform'>;
}
declare module 'slate-edit-blockquote/tests/enter-empty-middle/transform.js' {
  declare module.exports: $Exports<'slate-edit-blockquote/tests/enter-empty-middle/transform'>;
}
declare module 'slate-edit-blockquote/tests/enter-withtext-middle/transform.js' {
  declare module.exports: $Exports<'slate-edit-blockquote/tests/enter-withtext-middle/transform'>;
}
declare module 'slate-edit-blockquote/tests/schema-items-contain-blocks/transform.js' {
  declare module.exports: $Exports<'slate-edit-blockquote/tests/schema-items-contain-blocks/transform'>;
}
