// flow-typed signature: 0b78c39e3c1fdce55d4d981e36bc64b3
// flow-typed version: <<STUB>>/slate-edit-blockquote_v^0.6.1/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'slate-edit-blockquote'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'slate-edit-blockquote' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'slate-edit-blockquote/dist/changes/index' {
  declare module.exports: any;
}

declare module 'slate-edit-blockquote/dist/changes/unwrapBlockquote' {
  declare module.exports: any;
}

declare module 'slate-edit-blockquote/dist/changes/wrapInBlockquote' {
  declare module.exports: any;
}

declare module 'slate-edit-blockquote/dist/core' {
  declare module.exports: any;
}

declare module 'slate-edit-blockquote/dist/handlers/index' {
  declare module.exports: any;
}

declare module 'slate-edit-blockquote/dist/handlers/onBackspace' {
  declare module.exports: any;
}

declare module 'slate-edit-blockquote/dist/handlers/onEnter' {
  declare module.exports: any;
}

declare module 'slate-edit-blockquote/dist/handlers/onKeyDown' {
  declare module.exports: any;
}

declare module 'slate-edit-blockquote/dist/index' {
  declare module.exports: any;
}

declare module 'slate-edit-blockquote/dist/options' {
  declare module.exports: any;
}

declare module 'slate-edit-blockquote/dist/utils/getCurrentBlockquote' {
  declare module.exports: any;
}

declare module 'slate-edit-blockquote/dist/utils/index' {
  declare module.exports: any;
}

declare module 'slate-edit-blockquote/dist/utils/isSelectionInBlockquote' {
  declare module.exports: any;
}

declare module 'slate-edit-blockquote/dist/validation/index' {
  declare module.exports: any;
}

declare module 'slate-edit-blockquote/dist/validation/schema' {
  declare module.exports: any;
}

// Filename aliases
declare module 'slate-edit-blockquote/dist/changes/index.js' {
  declare module.exports: $Exports<'slate-edit-blockquote/dist/changes/index'>;
}
declare module 'slate-edit-blockquote/dist/changes/unwrapBlockquote.js' {
  declare module.exports: $Exports<'slate-edit-blockquote/dist/changes/unwrapBlockquote'>;
}
declare module 'slate-edit-blockquote/dist/changes/wrapInBlockquote.js' {
  declare module.exports: $Exports<'slate-edit-blockquote/dist/changes/wrapInBlockquote'>;
}
declare module 'slate-edit-blockquote/dist/core.js' {
  declare module.exports: $Exports<'slate-edit-blockquote/dist/core'>;
}
declare module 'slate-edit-blockquote/dist/handlers/index.js' {
  declare module.exports: $Exports<'slate-edit-blockquote/dist/handlers/index'>;
}
declare module 'slate-edit-blockquote/dist/handlers/onBackspace.js' {
  declare module.exports: $Exports<'slate-edit-blockquote/dist/handlers/onBackspace'>;
}
declare module 'slate-edit-blockquote/dist/handlers/onEnter.js' {
  declare module.exports: $Exports<'slate-edit-blockquote/dist/handlers/onEnter'>;
}
declare module 'slate-edit-blockquote/dist/handlers/onKeyDown.js' {
  declare module.exports: $Exports<'slate-edit-blockquote/dist/handlers/onKeyDown'>;
}
declare module 'slate-edit-blockquote/dist/index.js' {
  declare module.exports: $Exports<'slate-edit-blockquote/dist/index'>;
}
declare module 'slate-edit-blockquote/dist/options.js' {
  declare module.exports: $Exports<'slate-edit-blockquote/dist/options'>;
}
declare module 'slate-edit-blockquote/dist/utils/getCurrentBlockquote.js' {
  declare module.exports: $Exports<'slate-edit-blockquote/dist/utils/getCurrentBlockquote'>;
}
declare module 'slate-edit-blockquote/dist/utils/index.js' {
  declare module.exports: $Exports<'slate-edit-blockquote/dist/utils/index'>;
}
declare module 'slate-edit-blockquote/dist/utils/isSelectionInBlockquote.js' {
  declare module.exports: $Exports<'slate-edit-blockquote/dist/utils/isSelectionInBlockquote'>;
}
declare module 'slate-edit-blockquote/dist/validation/index.js' {
  declare module.exports: $Exports<'slate-edit-blockquote/dist/validation/index'>;
}
declare module 'slate-edit-blockquote/dist/validation/schema.js' {
  declare module.exports: $Exports<'slate-edit-blockquote/dist/validation/schema'>;
}
