// flow-typed signature: 71fc928fa877ca4b728fbfe5bca98f0f
// flow-typed version: <<STUB>>/unexpected_v^10.33.2/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'unexpected'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'unexpected' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'unexpected/bootstrap-unexpected-markdown' {
  declare module.exports: any;
}

declare module 'unexpected/externaltests/assertionSucceedsWhilePromiseIsPending.spec' {
  declare module.exports: any;
}

declare module 'unexpected/externaltests/deepObject.spec' {
  declare module.exports: any;
}

declare module 'unexpected/externaltests/failingAsync.spec' {
  declare module.exports: any;
}

declare module 'unexpected/externaltests/forgotToReturnPendingPromiseFromFailingItBlock.spec' {
  declare module.exports: any;
}

declare module 'unexpected/externaltests/forgotToReturnPendingPromiseFromItSuccessfulItBlock.spec' {
  declare module.exports: any;
}

declare module 'unexpected/externaltests/forgotToReturnPendingPromiseFromSuccessfulItBlock.spec' {
  declare module.exports: any;
}

declare module 'unexpected/externaltests/forgotToReturnPromiseRejectedInTheNextTick.spec' {
  declare module.exports: any;
}

declare module 'unexpected/externaltests/fullTrace.spec' {
  declare module.exports: any;
}

declare module 'unexpected/externaltests/node_modules/unexpected-bogus/index' {
  declare module.exports: any;
}

declare module 'unexpected/externaltests/notToErrorCaughtError.spec' {
  declare module.exports: any;
}

declare module 'unexpected/externaltests/successful.spec' {
  declare module.exports: any;
}

declare module 'unexpected/lib/addAdditionalPromiseMethods' {
  declare module.exports: any;
}

declare module 'unexpected/lib/assertions' {
  declare module.exports: any;
}

declare module 'unexpected/lib/AssertionString' {
  declare module.exports: any;
}

declare module 'unexpected/lib/createStandardErrorMessage' {
  declare module.exports: any;
}

declare module 'unexpected/lib/createWrappedExpectProto' {
  declare module.exports: any;
}

declare module 'unexpected/lib/defaultDepth' {
  declare module.exports: any;
}

declare module 'unexpected/lib/index' {
  declare module.exports: any;
}

declare module 'unexpected/lib/isPendingPromise' {
  declare module.exports: any;
}

declare module 'unexpected/lib/makeDiffResultBackwardsCompatible' {
  declare module.exports: any;
}

declare module 'unexpected/lib/makePromise' {
  declare module.exports: any;
}

declare module 'unexpected/lib/notifyPendingPromise' {
  declare module.exports: any;
}

declare module 'unexpected/lib/oathbreaker' {
  declare module.exports: any;
}

declare module 'unexpected/lib/specialCharRegExp' {
  declare module.exports: any;
}

declare module 'unexpected/lib/styles' {
  declare module.exports: any;
}

declare module 'unexpected/lib/throwIfNonUnexpectedError' {
  declare module.exports: any;
}

declare module 'unexpected/lib/types' {
  declare module.exports: any;
}

declare module 'unexpected/lib/Unexpected' {
  declare module.exports: any;
}

declare module 'unexpected/lib/UnexpectedError' {
  declare module.exports: any;
}

declare module 'unexpected/lib/useFullStackTrace' {
  declare module.exports: any;
}

declare module 'unexpected/lib/utils' {
  declare module.exports: any;
}

declare module 'unexpected/lib/workQueue' {
  declare module.exports: any;
}

declare module 'unexpected/rollup.config' {
  declare module.exports: any;
}

declare module 'unexpected/unexpected' {
  declare module.exports: any;
}

// Filename aliases
declare module 'unexpected/bootstrap-unexpected-markdown.js' {
  declare module.exports: $Exports<'unexpected/bootstrap-unexpected-markdown'>;
}
declare module 'unexpected/externaltests/assertionSucceedsWhilePromiseIsPending.spec.js' {
  declare module.exports: $Exports<'unexpected/externaltests/assertionSucceedsWhilePromiseIsPending.spec'>;
}
declare module 'unexpected/externaltests/deepObject.spec.js' {
  declare module.exports: $Exports<'unexpected/externaltests/deepObject.spec'>;
}
declare module 'unexpected/externaltests/failingAsync.spec.js' {
  declare module.exports: $Exports<'unexpected/externaltests/failingAsync.spec'>;
}
declare module 'unexpected/externaltests/forgotToReturnPendingPromiseFromFailingItBlock.spec.js' {
  declare module.exports: $Exports<'unexpected/externaltests/forgotToReturnPendingPromiseFromFailingItBlock.spec'>;
}
declare module 'unexpected/externaltests/forgotToReturnPendingPromiseFromItSuccessfulItBlock.spec.js' {
  declare module.exports: $Exports<'unexpected/externaltests/forgotToReturnPendingPromiseFromItSuccessfulItBlock.spec'>;
}
declare module 'unexpected/externaltests/forgotToReturnPendingPromiseFromSuccessfulItBlock.spec.js' {
  declare module.exports: $Exports<'unexpected/externaltests/forgotToReturnPendingPromiseFromSuccessfulItBlock.spec'>;
}
declare module 'unexpected/externaltests/forgotToReturnPromiseRejectedInTheNextTick.spec.js' {
  declare module.exports: $Exports<'unexpected/externaltests/forgotToReturnPromiseRejectedInTheNextTick.spec'>;
}
declare module 'unexpected/externaltests/fullTrace.spec.js' {
  declare module.exports: $Exports<'unexpected/externaltests/fullTrace.spec'>;
}
declare module 'unexpected/externaltests/node_modules/unexpected-bogus/index.js' {
  declare module.exports: $Exports<'unexpected/externaltests/node_modules/unexpected-bogus/index'>;
}
declare module 'unexpected/externaltests/notToErrorCaughtError.spec.js' {
  declare module.exports: $Exports<'unexpected/externaltests/notToErrorCaughtError.spec'>;
}
declare module 'unexpected/externaltests/successful.spec.js' {
  declare module.exports: $Exports<'unexpected/externaltests/successful.spec'>;
}
declare module 'unexpected/lib/addAdditionalPromiseMethods.js' {
  declare module.exports: $Exports<'unexpected/lib/addAdditionalPromiseMethods'>;
}
declare module 'unexpected/lib/assertions.js' {
  declare module.exports: $Exports<'unexpected/lib/assertions'>;
}
declare module 'unexpected/lib/AssertionString.js' {
  declare module.exports: $Exports<'unexpected/lib/AssertionString'>;
}
declare module 'unexpected/lib/createStandardErrorMessage.js' {
  declare module.exports: $Exports<'unexpected/lib/createStandardErrorMessage'>;
}
declare module 'unexpected/lib/createWrappedExpectProto.js' {
  declare module.exports: $Exports<'unexpected/lib/createWrappedExpectProto'>;
}
declare module 'unexpected/lib/defaultDepth.js' {
  declare module.exports: $Exports<'unexpected/lib/defaultDepth'>;
}
declare module 'unexpected/lib/index.js' {
  declare module.exports: $Exports<'unexpected/lib/index'>;
}
declare module 'unexpected/lib/isPendingPromise.js' {
  declare module.exports: $Exports<'unexpected/lib/isPendingPromise'>;
}
declare module 'unexpected/lib/makeDiffResultBackwardsCompatible.js' {
  declare module.exports: $Exports<'unexpected/lib/makeDiffResultBackwardsCompatible'>;
}
declare module 'unexpected/lib/makePromise.js' {
  declare module.exports: $Exports<'unexpected/lib/makePromise'>;
}
declare module 'unexpected/lib/notifyPendingPromise.js' {
  declare module.exports: $Exports<'unexpected/lib/notifyPendingPromise'>;
}
declare module 'unexpected/lib/oathbreaker.js' {
  declare module.exports: $Exports<'unexpected/lib/oathbreaker'>;
}
declare module 'unexpected/lib/specialCharRegExp.js' {
  declare module.exports: $Exports<'unexpected/lib/specialCharRegExp'>;
}
declare module 'unexpected/lib/styles.js' {
  declare module.exports: $Exports<'unexpected/lib/styles'>;
}
declare module 'unexpected/lib/throwIfNonUnexpectedError.js' {
  declare module.exports: $Exports<'unexpected/lib/throwIfNonUnexpectedError'>;
}
declare module 'unexpected/lib/types.js' {
  declare module.exports: $Exports<'unexpected/lib/types'>;
}
declare module 'unexpected/lib/Unexpected.js' {
  declare module.exports: $Exports<'unexpected/lib/Unexpected'>;
}
declare module 'unexpected/lib/UnexpectedError.js' {
  declare module.exports: $Exports<'unexpected/lib/UnexpectedError'>;
}
declare module 'unexpected/lib/useFullStackTrace.js' {
  declare module.exports: $Exports<'unexpected/lib/useFullStackTrace'>;
}
declare module 'unexpected/lib/utils.js' {
  declare module.exports: $Exports<'unexpected/lib/utils'>;
}
declare module 'unexpected/lib/workQueue.js' {
  declare module.exports: $Exports<'unexpected/lib/workQueue'>;
}
declare module 'unexpected/rollup.config.js' {
  declare module.exports: $Exports<'unexpected/rollup.config'>;
}
declare module 'unexpected/unexpected.js' {
  declare module.exports: $Exports<'unexpected/unexpected'>;
}
